-- ============================================================
-- TRIGGER: VALIDAÇÃO DE SALÁRIO
-- ============================================================
DROP TABLE PESSOA;
CREATE TABLE PESSOA(
    ID NUMBER(3) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    SALARIO NUMBER(7,2) NOT NULL
);
INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (1, 'MARIA', 99999.99);
INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (2, 'PAULO', -99.99);
COMMIT;
SELECT * FROM PESSOA;

CREATE OR REPLACE TRIGGER TRG_VALIDA_PESSOA
BEFORE INSERT OR UPDATE OF SALARIO
ON PESSOA
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO <= 0 OR :NEW.SALARIO > 10000 THEN
        RAISE_APPLICATION_ERROR(-20000, 'SALÁRIO FORA DA FAIXA DE VALOR');
    END IF;
END;
/

INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (3, 'CLAUDIA', 99999.99); -- erro esperado
INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (4, 'EVERTON', -99.99);   -- erro esperado
INSERT INTO PESSOA (ID, NOME, SALARIO) VALUES (5, 'LUIS', 1000);
COMMIT;
SELECT * FROM PESSOA WHERE ID = 5;
UPDATE PESSOA SET SALARIO = 2000 WHERE ID = 5;

-- ============================================================
-- ATIVIDADE: TRIGGER - VALIDAÇÃO DE MÉDIA E FREQUÊNCIA
-- ============================================================
DROP TABLE MEDIAS_ALUNO;
CREATE TABLE MEDIAS_ALUNO(
    RA NUMBER(7) PRIMARY KEY,
    MEDIA NUMBER(4,2) NOT NULL,
    FREQUENCIA NUMBER(5,2) NOT NULL
);

CREATE OR REPLACE TRIGGER TRG_VALIDA_MEDIA
BEFORE INSERT OR UPDATE OF MEDIA, FREQUENCIA
ON MEDIAS_ALUNO
FOR EACH ROW
BEGIN
    IF :NEW.MEDIA < 0 OR :NEW.MEDIA > 10 THEN
        RAISE_APPLICATION_ERROR(-20000, 'MÉDIA DEVE ESTAR ENTRE 0 E 10');
    END IF;
    IF :NEW.FREQUENCIA < 0 OR :NEW.FREQUENCIA > 100 THEN
        RAISE_APPLICATION_ERROR(-20001, 'FREQUÊNCIA DEVE ESTAR ENTRE 0 E 100');
    END IF;
END;
/

-- ============================================================
-- TABELAS DE APOIO: FUNCIONARIOS, LOG E SEQUENCES
-- ============================================================
DROP TABLE FUNCIONARIOS_AQB;
CREATE TABLE FUNCIONARIOS_AQB AS (SELECT * FROM EMPLOYEES);

DROP TABLE FUNCIONARIO_AQB_LOG;
CREATE TABLE FUNCIONARIO_AQB_LOG(
    ID_LOG NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    TIPO_OPERACAO CHAR(1) NOT NULL,
    SALARY_VELHO NUMBER(8,2) NULL,
    SALARY_NOVO NUMBER(8,2) NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    DTH_REGISTRO DATE NOT NULL,
    SQL_VOLTA VARCHAR(4000) NOT NULL
);

DROP SEQUENCE SEQ_FUNCIONARIO_AQB_LOG;
CREATE SEQUENCE SEQ_FUNCIONARIO_AQB_LOG
NOCACHE
NOCYCLE;

DROP TABLE LOG_EXECUCAO;
CREATE TABLE LOG_EXECUCAO(
    ID_LOG NUMBER PRIMARY KEY,
    ERRO NUMBER NOT NULL,
    DESC_ERRO VARCHAR2(1000) NOT NULL,
    LINHA_ERRO VARCHAR2(1000) NOT NULL,
    NOME_CODIGO VARCHAR2(30) NOT NULL,
    PARAMETROS VARCHAR2(1000) NOT NULL,
    DTH_ERRO DATE NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    RESOLVIDO CHAR(1) NOT NULL,
    DESC_RESOLVIDO VARCHAR2(1000)
);

DROP SEQUENCE SEQ_LOG_EXECUCAO;
CREATE SEQUENCE SEQ_LOG_EXECUCAO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- ============================================================
-- TRIGGER: LOG DE INSERT/UPDATE/DELETE COM SQL DE VOLTA
-- ============================================================
DROP TRIGGER TRG_LOG_FUNCIONARIOS_AQB;
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOS_AQB
BEFORE INSERT OR UPDATE OR DELETE
ON FUNCIONARIOS_AQB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'I', NULL, :NEW.SALARY, USER, SYSDATE,
            'DELETE FROM FUNCIONARIOS_AQB WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID || ';');
    ELSIF UPDATING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :NEW.EMPLOYEE_ID, 'U', :OLD.SALARY, :NEW.SALARY, USER, SYSDATE,
            'UPDATE FUNCIONARIOS_AQB SET SALARY = ' || :OLD.SALARY || ' WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID || ';');
    ELSIF DELETING THEN
        INSERT INTO FUNCIONARIO_AQB_LOG(ID_LOG, EMPLOYEE_ID, TIPO_OPERACAO, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, SQL_VOLTA)
        VALUES(SEQ_FUNCIONARIO_AQB_LOG.NEXTVAL, :OLD.EMPLOYEE_ID, 'D', :OLD.SALARY, NULL, USER, SYSDATE,
            'INSERT INTO FUNCIONARIOS_AQB (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES ('
            || TO_CHAR(:OLD.EMPLOYEE_ID) || ','
            || NVL2(:OLD.FIRST_NAME,    '''' || :OLD.FIRST_NAME    || '''', 'NULL') || ','
            || NVL2(:OLD.LAST_NAME,     '''' || :OLD.LAST_NAME     || '''', 'NULL') || ','
            || NVL2(:OLD.EMAIL,         '''' || :OLD.EMAIL         || '''', 'NULL') || ','
            || NVL2(:OLD.PHONE_NUMBER,  '''' || :OLD.PHONE_NUMBER  || '''', 'NULL') || ','
            || NVL2(:OLD.HIRE_DATE, 'TO_DATE(''' || TO_CHAR(:OLD.HIRE_DATE, 'YYYY-MM-DD HH24:MI:SS') || ''',''YYYY-MM-DD HH24:MI:SS'')', 'NULL') || ','
            || NVL2(:OLD.JOB_ID,        '''' || :OLD.JOB_ID        || '''', 'NULL') || ','
            || NVL(TO_CHAR(:OLD.SALARY),        'NULL') || ','
            || NVL(TO_CHAR(:OLD.COMMISSION_PCT),'NULL') || ','
            || NVL(TO_CHAR(:OLD.MANAGER_ID),    'NULL') || ','
            || NVL(TO_CHAR(:OLD.DEPARTMENT_ID), 'NULL')
            || ');');
    END IF;
END;
/

-- ============================================================
-- FUNCTION: AUMENTAR SALÁRIO COM LOG DE EXCEÇÃO
-- ============================================================
DROP FUNCTION FUNC_AUMENTA_SALARIO_AQB;
CREATE OR REPLACE FUNCTION FUNC_AUMENTA_SALARIO_AQB(P_PERC IN NUMBER)
RETURN NUMBER
IS
    V_RETORNO NUMBER(5);
    V_NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
    V_ERRO NUMBER;
    V_DESC_ERRO VARCHAR2(1000);
BEGIN
    IF P_PERC > 0 AND P_PERC <= 15 THEN
        FOR I IN (
            SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM FUNCIONARIOS_AQB
            WHERE JOB_ID != 'AD_PRES' AND JOB_ID != 'AD_VP')
        LOOP
            IF I.SALARY < 10000 THEN
                V_NOVO_SALARIO := I.SALARY * (1 + P_PERC/100);
            ELSE
                V_NOVO_SALARIO := I.SALARY;
            END IF;
        END LOOP;
        V_RETORNO := 0;
    ELSE
        V_RETORNO := -1;
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;
        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
            'FUNC_AUMENTA_SALARIO_AQB', 'P_PERC = ' || P_PERC, SYSDATE, USER, 'N', NULL);
        COMMIT;
        RETURN SQLCODE;
END;
/

-- ============================================================
-- FUNCTION: INSERIR FABRICANTE COM VALIDAÇÕES E LOG
-- ============================================================
/*
  FUNC_INSERIRFABRICANTE
  Retornos:
   0  → Sucesso
  -1  → P_ID_FAB nulo
  -2  → P_ID_FAB não inteiro
  -3  → P_ID_FAB fora do intervalo 1–9999
  -4  → ID_FAB já existe na tabela
  -5  → P_NOME nulo ou vazio
  -6  → P_NOME com mais de 120 caracteres
  -7  → P_NOME já existe (comparação sem acento, case-insensitive)
  -8  → P_APELIDO informado com mais de 60 caracteres
*/
CREATE OR REPLACE FUNCTION FUNC_INSERIRFABRICANTE (
    P_ID_FAB  IN FABRICANTE.ID_FAB%TYPE,
    P_NOME    IN FABRICANTE.NOME%TYPE,
    P_APELIDO IN FABRICANTE.APELIDO%TYPE
)
RETURN NUMBER
IS
    V_RETORNO   NUMBER(5);
    V_QTDE      NUMBER;
    V_ERRO      NUMBER;
    V_DESC_ERRO VARCHAR2(1000);
BEGIN
    IF P_ID_FAB IS NULL THEN
        V_RETORNO := -1;
    ELSIF P_ID_FAB <> TRUNC(P_ID_FAB) THEN
        V_RETORNO := -2;
    ELSIF P_ID_FAB NOT BETWEEN 1 AND 9999 THEN
        V_RETORNO := -3;
    ELSE
        SELECT COUNT(*) INTO V_QTDE FROM FABRICANTE WHERE ID_FAB = P_ID_FAB;
        IF V_QTDE > 0 THEN
            V_RETORNO := -4;
        ELSE
            IF P_NOME IS NULL OR LENGTH(TRIM(P_NOME)) = 0 THEN
                V_RETORNO := -5;
            ELSIF LENGTH(TRIM(P_NOME)) > 120 THEN
                V_RETORNO := -6;
            ELSE
                SELECT COUNT(*) INTO V_QTDE FROM FABRICANTE
                WHERE TRANSLATE(UPPER(TRIM(NOME)),    'ÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÄËÏÖÜÇ', 'AEIOUAEIOUAOAEIOUAEIOUC')
                    = TRANSLATE(UPPER(TRIM(P_NOME)),  'ÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÄËÏÖÜÇ', 'AEIOUAEIOUAOAEIOUAEIOUC');
                IF V_QTDE > 0 THEN
                    V_RETORNO := -7;
                ELSE
                    IF P_APELIDO IS NOT NULL AND LENGTH(TRIM(P_APELIDO)) > 60 THEN
                        V_RETORNO := -8;
                    ELSE
                        INSERT INTO FABRICANTE (ID_FAB, NOME, APELIDO)
                        VALUES (P_ID_FAB, TRIM(P_NOME), TRIM(P_APELIDO));
                        V_RETORNO := 0;
                    END IF;
                END IF;
            END IF;
        END IF;
    END IF;
    COMMIT;
    RETURN V_RETORNO;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        V_ERRO := SQLCODE;
        V_DESC_ERRO := SQLERRM;
        INSERT INTO LOG_EXECUCAO
            (ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMETROS, DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
        VALUES
            (SEQ_LOG_EXECUCAO.NEXTVAL, V_ERRO, V_DESC_ERRO, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
            'FUNC_INSERIRFABRICANTE',
            'P_ID_FAB = ' || P_ID_FAB || ' | P_NOME = ' || P_NOME || ' | P_APELIDO = ' || P_APELIDO,
            SYSDATE, USER, 'N', NULL);
        COMMIT;
        RETURN SQLCODE;
END;
/